import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const root = new URL('../src/ai/phone/', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('manifest.json', root), 'utf8'));
const bytes = readFileSync(new URL('walt-player.wasm', root));
if (createHash('sha256').update(bytes).digest('hex') !== manifest.wasm_sha256) throw new Error('Walt asset and manifest differ; import a matched build.');
const module = new WebAssembly.Module(bytes);
const imports = WebAssembly.Module.imports(module).map((i) => `${i.module}.${i.name}`).sort();
if (JSON.stringify(imports) !== JSON.stringify(['walt_host.checkpoint','walt_host.now_us'])) throw new Error(`Unexpected host capabilities: ${imports}`);
console.log(`Verified ${manifest.player} · ${bytes.length} bytes`);
